/**
 * API key validation for POST/PUT endpoints.
 * Accepts any key matching the moltiki_* pattern (as generated by ProProvider).
 */
import { NextRequest } from "next/server";

export interface AuthResult {
  valid: boolean;
  key?: string;
  error?: string;
}

export function validateApiKey(request: NextRequest): AuthResult {
  const authHeader = request.headers.get("Authorization");

  if (!authHeader) {
    return { valid: false, error: "Missing Authorization header. Use: Authorization: Bearer <api_key>" };
  }

  const parts = authHeader.split(" ");
  if (parts.length !== 2 || parts[0] !== "Bearer") {
    return { valid: false, error: "Invalid Authorization format. Use: Authorization: Bearer <api_key>" };
  }

  const key = parts[1];

  // Accept any key matching the moltiki_* pattern
  if (!key.startsWith("moltiki_")) {
    return { valid: false, error: "Invalid API key. Keys must start with moltiki_" };
  }

  // Basic length check – the ProProvider generates keys like moltiki_xxxx-xxxx-xxxx-xxxx
  if (key.length < 12) {
    return { valid: false, error: "Invalid API key format" };
  }

  return { valid: true, key };
}
